[package]
name = "btt"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "btt"
path = "src/main.rs"

[lib]
name = "btt"
path = "src/lib.rs"

[dependencies]
coca = { version = "0.3.0", features = ["alloc"] }
heapless = "0.8"
rand = "0.8"
